### ISSUE TITLE
failed to configure project

### ISSUE THREAD

**Issue by NikitaWeW** [frozein/VkGalaxy#3]
`PS path\to\VkGalaxy> cmake . -G "MinGW Makefiles" -D CMAKE_BUILD_TYPE=debug; if($?) {cmake --build .;} `
`CMake Error at C:/cmake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):    `
`  Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) (found                            `
`  version "")                                                                                          `
`Call Stack (most recent call first):                                                                   `
`  C:/cmake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)   `
`  C:/cmake/share/cmake-3.29/Modules/FindVulkan.cmake:594 (find_package_handle_standard_args)           `
`  CMakeLists.txt:29 (find_package)                                                                     `
`                                                                                                       `
`                                                                                                       `
`-- Configuring incomplete, errors occurred!         `                                                   

However, i have VulkanSDK installed. maybe i did something wrong?

**Comment by frozein** [comment]
Make sure you have installed VulkanSDK somewhere accessible by your package manager. If you aren't using a package manager, you may need to point cmake to the SDK installation directly by specifying CMAKE_MODULE_PATH.
