### ISSUE TITLE
 Build Failure on Debian 12

### ISSUE THREAD

**Issue by nilimdaimari** [frozein/VkGalaxy#4]
I cloned the VkGalaxy repository and encountered build issues on Debian 12. Please advise on potential solutions.

System Info:

OS: Debian 12

**Comment by frozein** [comment]
Can you tell me what the error is specifically? I don't have access to a Debian system.

**Comment by nilimdaimari** [comment]
Here are the errors I encounter when compiling. Any guidance or feedback on resolving these would be greatly appreciated!

[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /<" ">/VkGalaxy/build --config Debug --target all -j 10 --
[build] sh: 0: cannot open shader_compile.sh: No such file
[build] gmake[2]: *** [CMakeFiles/vkgalaxy_shaders.dir/build.make:74: CMakeFiles/vkgalaxy_shaders] Error 2
[build] gmake[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/vkgalaxy_shaders.dir/all] Error 2
[build] gmake[1]: *** Waiting for unfinished jobs....
[build] [100%] Built target vkgalaxy
[build] gmake: *** [Makefile:91: all] Error 2
[proc] The command: /usr/bin/cmake --build /home/<" ">t/VkGalaxy/build --config Debug --target all -j 10 -- exited with code: 2
[driver] Build completed: 00:00:00.090
[build] Build finished with exit code 2

**Comment by nilimdaimari** [comment]
> Can you tell me what the error is specifically? I don't have access to a Debian system.



--------------------
Here are the errors I encounter when compiling. Any guidance or feedback on resolving these would be greatly appreciated!

[build] Starting build
[proc] Executing command: /usr/bin/cmake --build /<" ">/VkGalaxy/build --config Debug --target all -j 10 --
[build] sh: 0: cannot open shader_compile.sh: No such file
[build] gmake[2]: *** [CMakeFiles/vkgalaxy_shaders.dir/build.make:74: CMakeFiles/vkgalaxy_shaders] Error 2
[build] gmake[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/vkgalaxy_shaders.dir/all] Error 2
[build] gmake[1]: *** Waiting for unfinished jobs....
[build] [100%] Built target vkgalaxy
[build] gmake: *** [Makefile:91: all] Error 2
[proc] The command: /usr/bin/cmake --build /home/<" ">t/VkGalaxy/build --config Debug --target all -j 10 -- exited with code: 2
[driver] Build completed: 00:00:00.090
[build] Build finished with exit code 2

**Comment by frozein** [comment]
Try running `cmake .` and from the base `VkGalaxy` directory, not a separate build directory. The shader compilation script isn't configured to handle a variable build directory yet unfortunately.
